version: '3'

vars:
  BINARY_NAME: k1s
  BUILD_DIR: ./bin
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "none"
  DATE:
    sh: date -u '+%Y-%m-%dT%H:%M:%SZ'
  LDFLAGS: -s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.date={{.DATE}}

tasks:
  default:
    desc: Build and run k1s
    cmds:
      - task: build
      - task: run

  build:
    desc: Build k1s binary
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -ldflags "{{.LDFLAGS}}" -o {{.BUILD_DIR}}/{{.BINARY_NAME}} ./cmd/k1s
    sources:
      - "**/*.go"
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  run:
    desc: Run k1s
    cmds:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f k1s

  install:
    desc: Install k1s to /usr/local/bin
    deps: [build]
    cmds:
      - sudo cp {{.BUILD_DIR}}/{{.BINARY_NAME}} /usr/local/bin/

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  release:
    desc: "Create a new release (usage: task release -- v0.2.0)"
    cmds:
      - git tag {{.CLI_ARGS}}
      - git push k1s {{.CLI_ARGS}}
      - echo "Release {{.CLI_ARGS}} created! Check https://github.com/andrebassi/k1s/actions"

  macports:update:
    desc: Update MacPorts Portfile checksums for a release
    vars:
      TAG:
        sh: git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.1"
      VERSION:
        sh: git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || echo "0.1.1"
    cmds:
      - |
        echo "Updating Portfile for {{.TAG}}..."
        TARBALL_URL="https://github.com/andrebassi/k1s/archive/refs/tags/{{.TAG}}.tar.gz"
        echo "Downloading tarball from $TARBALL_URL"

        SHA256=$(curl -sL "$TARBALL_URL" | shasum -a 256 | awk '{print $1}')
        RMD160=$(curl -sL "$TARBALL_URL" | openssl dgst -rmd160 | awk '{print $2}')
        SIZE=$(curl -sL "$TARBALL_URL" | wc -c | tr -d ' ')

        echo ""
        echo "=== Portfile checksums for {{.TAG}} ==="
        echo "go.setup            github.com/andrebassi/k1s {{.VERSION}} v"
        echo ""
        echo "checksums           rmd160  $RMD160 \\"
        echo "                    sha256  $SHA256 \\"
        echo "                    size    $SIZE"
        echo ""
        echo "Update ports/sysutils/k1s/Portfile with these values"

  macports:submit:
    desc: Instructions for submitting to MacPorts
    cmds:
      - |
        echo ""
        echo "=== MacPorts Submission Guide ==="
        echo ""
        echo "1. Fork the macports-ports repository:"
        echo "   https://github.com/macports/macports-ports"
        echo ""
        echo "2. Clone your fork:"
        echo "   git clone https://github.com/YOUR_USERNAME/macports-ports"
        echo "   cd macports-ports"
        echo ""
        echo "3. Create a new branch:"
        echo "   git checkout -b add-k1s-port"
        echo ""
        echo "4. Copy the Portfile:"
        echo "   mkdir -p sysutils/k1s"
        echo "   cp /path/to/k1s/ports/sysutils/k1s/Portfile sysutils/k1s/"
        echo ""
        echo "5. Test locally (requires MacPorts installed):"
        echo "   sudo port -v test sysutils/k1s"
        echo ""
        echo "6. Commit and push:"
        echo "   git add sysutils/k1s/Portfile"
        echo "   git commit -m 'sysutils/k1s: new port, Kubernetes TUI Debugger'"
        echo "   git push origin add-k1s-port"
        echo ""
        echo "7. Create Pull Request at:"
        echo "   https://github.com/macports/macports-ports/pulls"
        echo ""
        echo "Reference: https://guide.macports.org/chunked/project.contributing.html"
        echo ""

  # ============================================
  # Installation Tests
  # ============================================

  test:brew:install:
    desc: Install k1s via Homebrew
    cmds:
      - brew tap andrebassi/k1s
      - brew install k1s
      - echo "✅ Homebrew installation complete"

  test:brew:upgrade:
    desc: Upgrade k1s via Homebrew
    cmds:
      - brew upgrade k1s || echo "Already at latest version"

  test:brew:uninstall:
    desc: Uninstall k1s via Homebrew
    cmds:
      - brew uninstall k1s
      - brew untap andrebassi/k1s
      - echo "✅ Homebrew uninstall complete"

  test:brew:verify:
    desc: Verify k1s Homebrew installation
    cmds:
      - |
        echo "=== Homebrew k1s Verification ==="
        echo ""
        echo "📍 Binary location:"
        which k1s
        echo ""
        echo "📦 Version:"
        k1s --version
        echo ""
        echo "❓ Help:"
        k1s --help | head -20
        echo "..."
        echo ""
        echo "✅ Homebrew verification complete"

  test:brew:
    desc: Full Homebrew test (install, verify, uninstall)
    cmds:
      - task: test:brew:install
      - task: test:brew:verify
      - echo ""
      - echo "Run 'task test:brew:uninstall' to remove"

  test:macports:install:
    desc: Install k1s via MacPorts (requires MacPorts)
    cmds:
      - |
        if ! command -v port &> /dev/null; then
          echo "❌ MacPorts not installed"
          echo "Install from: https://www.macports.org/install.php"
          exit 1
        fi
        sudo port install k1s
        echo "✅ MacPorts installation complete"

  test:macports:uninstall:
    desc: Uninstall k1s via MacPorts
    cmds:
      - |
        if ! command -v port &> /dev/null; then
          echo "❌ MacPorts not installed"
          exit 1
        fi
        sudo port uninstall k1s
        echo "✅ MacPorts uninstall complete"

  test:macports:verify:
    desc: Verify k1s MacPorts installation
    cmds:
      - |
        if ! command -v port &> /dev/null; then
          echo "❌ MacPorts not installed"
          exit 1
        fi
        echo "=== MacPorts k1s Verification ==="
        echo ""
        echo "📍 Binary location:"
        which k1s
        echo ""
        echo "📦 Version:"
        k1s --version
        echo ""
        echo "❓ Help:"
        k1s --help | head -20
        echo "..."
        echo ""
        echo "✅ MacPorts verification complete"

  test:macports:local:
    desc: Test Portfile locally (build from source)
    cmds:
      - |
        if ! command -v port &> /dev/null; then
          echo "❌ MacPorts not installed"
          echo "Install from: https://www.macports.org/install.php"
          exit 1
        fi
        echo "Testing local Portfile..."
        cd {{.ROOT_DIR}}
        sudo port -v test ports/sysutils/k1s
        echo "✅ Local Portfile test complete"

  test:macports:
    desc: Full MacPorts test (requires MacPorts installed)
    cmds:
      - task: test:macports:install
      - task: test:macports:verify
      - echo ""
      - echo "Run 'task test:macports:uninstall' to remove"

  test:all:
    desc: Test all installation methods
    cmds:
      - |
        echo "=== Testing All Installation Methods ==="
        echo ""
        echo "1. Testing Homebrew..."
        task test:brew:install
        task test:brew:verify
        echo ""
        echo "2. Checking MacPorts..."
        if command -v port &> /dev/null; then
          task test:macports:install
          task test:macports:verify
        else
          echo "⚠️  MacPorts not installed, skipping"
        fi
        echo ""
        echo "=== All tests complete ==="
